### ISSUE TITLE
Output selection panel is blank after 1.208.0 update.

### ISSUE THREAD

**Issue by macerg** [prezz/MusicPlayerRemote#13] opened 2021-01-26 08:29 UTC
Latest update broke  output selection panel. Is now blank. Any chance of also reinstating the 'local' album art server support? That's where I store all of my album art, all 20,000 albums of it! MP
![Screenshot_20210126-153224](https://user-images.githubusercontent.com/4559048/105820147-c317c400-5feb-11eb-8b2e-2bdfdd7321ab.jpg)
D 19.19

**Comment by prezz** [comment] 2021-01-26 19:51
Haven't been able to reproduce on my setup, but assume the reason for the issue is that some code to read the "plugin" property of https://www.musicpd.org/doc/html/protocol.html#audio-output-devices has been introduced. My guess is that older versions of MPD does not return this property even though the documentation does not clarify this. Anyway the issue should be resolved in 1.129.0 such it can handle responses with and without this property in the response.

**Closed** 2021-01-26 19:52 UTC

**Comment by macerg** [comment] 2021-01-27 00:48
Yes, that's fixed it, thanks.Regards,Richard MaceOn 27 Jan 2021 02:51, Mikael Heinze <notifications@github.com> wrote:
Haven't been able to reproduce on my setup, but assume the reason for the issue is that some code to read the "plugin" property of https://www.musicpd.org/doc/html/protocol.html#audio-output-devices has been introduced. My guess is that older versions of MPD does not return this property even though the documentation does not clarify this. Anyway the issue should be resolved in 1.129.0 such it can handle responses with and without this property in the response.
